// ze_canning.res resource file.

maps/ze_canning.res
gfx/env/canningup.tga
gfx/env/canningdn.tga
gfx/env/canninglf.tga
gfx/env/canningrt.tga
gfx/env/canningft.tga
gfx/env/canningbk.tga
sprites/ze_canning/flare1.spr
models/ze_canning/tree.mdl
models/ze_canning/bush.mdl
sound/ze_canning/wind1.wav
models/ze_canning/dead3.mdl
sound/ze_canning/dead.wav
sprites/ze_canning/particles.spr
models/ze_canning/mouthpiece.mdl
sound/ze_canning/fan2.wav
sound/ze_canning/bighum.wav
models/ze_canning/dead4.mdl
sound/ze_canning/dead2.wav
sound/ze_canning/locked1.wav
sound/ze_canning/locked2.wav
models/ze_canning/dead2.mdl
sound/ze_canning/scream2.wav
sound/ze_canning/noise.wav
sound/ze_canning/noise2.wav
sound/ze_canning/drips.wav
sound/ze_canning/scream1.wav
models/ze_canning/dead5.mdl
sound/ze_canning/bustflesh2.wav
sound/ze_canning/bustflesh1.wav
sprites/ze_canning/ghost.spr
sound/ze_canning/scream4.wav
sound/ze_canning/scream3.wav
sound/ze_canning/noise3.wav
sound/ze_canning/wind2.wav
sound/ze_canning/strike.wav
sound/ze_canning/wind3.wav
sound/ze_canning/fallscream.wav
sound/ze_canning/scream5.wav
sound/ze_canning/jetflyby1.wav
models/ze_canning/table.mdl
models/ze_canning/boxes.mdl
models/ze_canning/machine.mdl
sound/ze_canning/siren.wav
sound/ze_canning/generator.wav
sprites/ze_canning/teleport.spr
sound/ze_canning/attention.wav
overviews/ze_canning.bmp
overviews/ze_canning.txt
